version: '3.5'
networks:
  frostaura:
    external:
      name: frostaura
services:
  jesse-bot:
    image: frostaura/jesse:latest
    container_name: jesse-bot
    volumes:
      - ./tmp/jesse-config/:/app/config/
      - ./tmp/jesse-storage/:/app/storage/
      - ./tmp/jesse-logs/:/app/logs/
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - frostaura

volumes:
  jesse-config:
  jesse-storage:
  jesse-logs:
